Repository prgrms-web-devcourse-final-project/WEB1_1_ALL-I_FE, pull requests merged in 2024-11, with the labels that each got.

#2 setting: 세팅동작 테스트
  src/App.tsx
Labels: design

#6 feat: 페이지별 컴포넌트 생성 및 라우트 파일 정의
  eslint.config.js
  src/App.css
  src/App.tsx
  src/apis/dummy.ts
  src/components/feature/dummy.ts
  src/components/layout/RootLayout/RootLayout.tsx
  src/index.css
  src/mocks/dummy.ts
  src/pages/categories/CategoriesPage.style.tsx
  src/pages/categories/CategoriesPage.tsx
  src/pages/categories/edit/CategoriesEditPage.tsx
  src/pages/categories/new/CategoriesNewPage.tsx
  src/pages/chat/ChatPage.tsx
  src/pages/error/ErrorPage.tsx
  src/pages/group/GroupPage.tsx
  src/pages/group/edit/GroupEditPage.tsx
  src/pages/group/new/GroupNewPage.tsx
  src/pages/group/schedule/edit/GroupScheduleEditPage.tsx
  src/pages/group/schedule/new/GroupScheduleNewPage.tsx
  src/pages/group/todo/edit/GroupTodoEditPage.tsx
  src/pages/group/todo/new/GroupTodoNewPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/login/LoginPage.style.ts
  src/pages/login/LoginPage.tsx
  src/pages/main/MainPage.tsx
  src/pages/main/schedule/edit/MainScheduleEditPage.tsx
  src/pages/main/schedule/new/MainScheduleNewPage.tsx
  src/pages/main/todo/edit/MainTodoEditPage.tsx
  src/pages/main/todo/new/MainTodoNewPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/edit/MyEditPage.tsx
  src/pages/notifications/NotificationsPage.tsx
  src/pages/signup/SignupPage.tsx
  src/routes.tsx
  src/store/dummy.ts
  src/types/dummy.ts
  src/utils/dummy.ts
Labels: setting

#8 feat: 글로벌 스타일 시스템 구축
  src/index.css
Labels: feature

#10 feat: 글로벌 스타일 시스템 추가 구축
  src/index.css
Labels: feature

#17 feat: TextButton 컴포넌트 제작, 스토리북에 글로벌 스타일 적용
  .storybook/preview.ts
  src/components/common/TextButton/TextButton.stories.tsx
  src/components/common/TextButton/TextButton.style.ts
  src/components/common/TextButton/TextButton.tsx
Labels: feature

#21 refactor: 텍스트버튼 컴포넌트 수정
  src/components/common/TextButton/TextButton.stories.tsx
  src/components/common/TextButton/TextButton.tsx
Labels: refactor

#25 feat: 수정/삭제 모달 컴포넌트 제작
  src/components/common/EditDeleteModal/EditDeleteModal.stories.tsx
  src/components/common/EditDeleteModal/EditDeleteModal.style.ts
  src/components/common/EditDeleteModal/EditDeleteModal.tsx
Labels: feature

#26 design: 카테고리 원형 색상 퍼블리싱
  src/components/common/Circle/Circle.stories.tsx
  src/components/common/Circle/Circle.style.tsx
  src/components/common/Circle/Circle.tsx
  src/components/common/Circle/CircleInput.stories.tsx
  src/components/common/Circle/CircleInput.tsx
  src/hooks/useCircleInput.ts
  src/index.css
Labels: feature, design

#29 feat: 시간입력 컴포넌트 구현 및 스토리북 추가
  src/components/common/TimeInput/TimeInput.stories.tsx
  src/components/common/TimeInput/TimeInput.style.ts
  src/components/common/TimeInput/TimeInput.tsx
Labels: feature, design

#33 refactor: 버튼 컴포넌트 스토리북 경로 수정, 버튼 타입 추가 제작
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.style.ts
  src/components/common/Button/Button.tsx
Labels: feature, refactor

#35 refactor: 텍스트버튼, 수정/삭제 모달 스토리북 경로 변경
  src/components/common/EditDeleteModal/EditDeleteModal.stories.tsx
  src/components/common/TextButton/TextButton.stories.tsx
Labels: feature, refactor

#31 feat: 삭제 확인 모달 구현
  src/components/common/DeleteConfirm/DeleteConfirm.stories.tsx
  src/components/common/DeleteConfirm/DeleteConfirm.style.ts
  src/components/common/DeleteConfirm/DeleteConfirm.tsx
Labels: feature

#39 feat:프로필 이미지 컴포넌트 구현 및 스토리북 추가
  src/components/common/ProfileImg/ProfileImg.stories.tsx
  src/components/common/ProfileImg/ProfileImg.style.ts
  src/components/common/ProfileImg/ProfileImg.tsx
Labels: design

#40 feat: 토글 컴포넌트 제작
  src/components/common/Toggle/Toggle.stories.tsx
  src/components/common/Toggle/Toggle.style.ts
  src/components/common/Toggle/Toggle.tsx
Labels: feature

#43 design:텍스트 css 설정
  src/components/common/TextSetting/TextSetting.style.ts
  src/components/common/TextSetting/TextSetting.tsx
Labels: design

#44 feat: 아이콘 버튼들 구현
  package.json
  src/assets/icons/alarm.svg
  src/assets/icons/back.svg
  src/assets/icons/camera.svg
  src/assets/icons/chatbot.svg
  src/assets/icons/dots.svg
  src/assets/icons/filtering.svg
  src/assets/icons/group.svg
  src/assets/icons/home.svg
  src/assets/icons/plus.svg
  src/assets/icons/profile.svg
  src/assets/icons/setting.svg
  src/assets/icons/trashcan.svg
  src/types/custom.d.ts
  vite.config.ts
Labels: feature

#46 Feature/#30 droplist
  package.json
  src/components/common/SelectList/Category/Category.stories.tsx
  src/components/common/SelectList/Category/CategorySelect.style.ts
  src/components/common/SelectList/Category/CategorySelect.tsx
  src/components/common/SelectList/Group/ GroupSelect.stories.tsx
  src/components/common/SelectList/Group/GroupSelect.style.ts
  src/components/common/SelectList/Group/GroupSelect.tsx
Labels: feature, design

#48 design: 투두/일정 리스트에 들어가는 내용 퍼블리싱
  src/components/common/ListBar/ListBar.stories.tsx
  src/components/common/ListBar/ListBar.style.tsx
  src/components/common/ListBar/ListBar.tsx
  src/components/common/ScheduleList/ScheduleItem.stories.tsx
  src/components/common/ScheduleList/ScheduleItem.style.tsx
  src/components/common/ScheduleList/ScheduleItem.tsx
  src/components/common/TextDate/TextDate.stories.tsx
  src/components/common/TextDate/TextDate.style.tsx
  src/components/common/TextDate/TextDate.tsx
  src/components/common/TodoList/TodoItem.stories.tsx
  src/components/common/TodoList/TodoItem.style.tsx
  src/components/common/TodoList/TodoItem.tsx
  src/hooks/useCircleInput.ts
  src/hooks/useTodoItem.ts
Labels: design

#50 design: rootlayout css 설정
  src/components/layout/RootLayout/RootLayout.style.tsx
  src/index.css
Labels: design

#52 feat:하단 내비게이션바 구현
  src/components/layout/NavBar/NavBar.style.ts
  src/components/layout/NavBar/NavBar.tsx
  src/components/layout/RootLayout/RootLayout.tsx
Labels: feature, design

#54 refactor: 인터페이스 분리 및 코드 수정
  src/components/common/DateInput/DateInput.style.ts
  src/components/common/DateInput/DateInput.tsx
  src/components/common/SelectList/Category/CategorySelect.style.ts
  src/components/common/SelectList/Category/CategorySelect.tsx
  src/components/common/SelectList/Group/GroupSelect.style.ts
  src/components/common/SelectList/Group/GroupSelect.tsx
  src/components/common/TextInput/TextInput.stories.tsx
  src/components/common/TextInput/TextInput.style.ts
  src/components/common/TextInput/TextInput.tsx
  src/components/common/TimeInput/TimeInput.stories.tsx
  src/components/common/TimeInput/TimeInput.style.ts
  src/components/common/TimeInput/TimeInput.tsx
  src/types/input.types.ts
  src/types/select.types.ts
Labels: design, refactor

#62 feat: header 구현 및 루트레이아웃 수정
  src/components/layout/Header/Header.style.ts
  src/components/layout/Header/Header.tsx
  src/components/layout/RootLayout/RootLayout.tsx
Labels: feature, design

#61 refactor: common/Calendar 폴더 컨벤션 적용
  src/components/common/Calendar/Calendar.style.ts
  src/components/common/Calendar/Calendar.tsx
  src/components/common/calendar/week/CalendarWeek.tsx
  src/pages/home/HomePage.tsx
Labels: refactor

#64 design: 회원가입 페이지 퍼블리싱
  src/components/common/Button/Button.tsx
  src/components/common/TextInput/TextInput.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/NavBar/NavBar.tsx
  src/hooks/useSignupForm.ts
  src/pages/signup/SignupPage.style.tsx
  src/pages/signup/SignupPage.tsx
Labels: feature, design

#65 feat: 카테고리 생성 페이지 개발
  src/components/feature/CategoryList/CategoryList.style.ts
  src/components/feature/CategoryList/CategoryList.tsx
  src/pages/categories/CategoriesPage.style.ts
  src/pages/categories/CategoriesPage.tsx
Labels: feature, design

#67 fix: 버튼 컴포넌트 type 추가
  src/pages/categories/CategoriesPage.tsx
Labels: fix

#72 refactor: 스타일 파일 import 변수명 변경 및 빨간색 컬러 변경
  src/components/common/Button/Button.tsx
  src/components/common/DeleteConfirm/DeleteConfirm.tsx
  src/components/common/EditDeleteModal/EditDeleteModal.style.ts
  src/components/common/EditDeleteModal/EditDeleteModal.tsx
  src/components/common/TextButton/TextButton.tsx
  src/components/common/Toggle/Toggle.tsx
Labels: refactor

#70 feat: 토스트 커스텀훅 구현
  package.json
  src/App.tsx
  src/hooks/useToast.ts
Labels: feature

#76 design: 수정/삭제 모달창 수정
  src/components/common/EditDeleteModal/EditDeleteModal.style.ts
  src/components/common/EditDeleteModal/EditDeleteModal.tsx
  src/components/feature/CategoryList/CategoryList.tsx
  src/index.css
Labels: design

#73 feat: 카테고리 생성 페이지 개발
  src/components/common/Circle/Circle.style.tsx
  src/components/common/Circle/CircleInput.tsx
  src/components/layout/NavBar/NavBar.style.ts
  src/hooks/useCategoryForm.ts
  src/hooks/useCircleInput.ts
  src/index.css
  src/pages/categories/new/CategoriesEditPage.style.ts
  src/pages/categories/new/CategoriesNewPage.tsx
Labels: feature, design

#78 feat: 투두/일정의 생성/수정 페이지 제작
  src/components/common/DateInput/DateInput.tsx
  src/components/common/SelectList/Category/CategorySelect.style.ts
  src/components/common/SelectList/Category/CategorySelect.tsx
  src/components/common/TimeInput/TimeInput.tsx
  src/components/form/TodoScheduleForm/TodoScheduleForm.style.ts
  src/components/form/TodoScheduleForm/TodoScheduleForm.tsx
  src/hooks/useTodoScheduleForm.ts
  src/pages/main/schedule/edit/MainScheduleEditPage.tsx
  src/pages/main/schedule/new/MainScheduleNewPage.tsx
  src/pages/main/todo/edit/MainTodoEditPage.tsx
  src/pages/main/todo/new/MainTodoNewPage.tsx
  src/types/input.types.ts
  src/types/select.types.ts
Labels: feature, design
