Repository prgrms-web-devcourse-final-project/WEB1_1_ALL-I_FE, pull requests merged in 2024-12, with the labels that each got.

#81 design: 로그인 페이지 퍼블리싱
  src/components/layout/Header/Header.tsx
  src/components/layout/NavBar/NavBar.tsx
  src/hooks/useLoginForm.ts
  src/pages/login/LoginPage.style.ts
  src/pages/login/LoginPage.tsx
Labels: feature, design

#85 feat: 달력 스타일링 마무리
  src/components/common/Calendar/Calendar.style.ts
  src/components/common/Calendar/Calendar.tsx
  src/mocks/PERSONAL_EVENT_DATA.ts
  src/mocks/PERSONAL_TODO_DATA.ts
  src/pages/home/HomePage.tsx
  src/types/dummy.ts
Labels: feature, design

#88 feat: 일정, 투두 컴포넌트 기능 구현
  src/components/common/ScheduleList/ScheduleItem.style.tsx
  src/components/common/ScheduleList/ScheduleItem.tsx
  src/components/common/TodoList/TodoItem.style.tsx
  src/components/common/TodoList/TodoItem.tsx
  src/components/feature/CategoryList/CategoryList.tsx
  src/components/feature/EditDeleteIcon/EditDelete.style.ts
  src/components/feature/EditDeleteIcon/EditDeleteIcon.tsx
  src/components/feature/MainCategoryButton/MainCategoryButton.style.ts
  src/components/feature/MainCategoryButton/MainCategoryButton.tsx
  src/components/feature/PlusButton/PlusButton.style.ts
  src/components/feature/PlusButton/PlusButton.tsx
  src/utils/format.ts
Labels: feature, design, refactor

#89 feat: mainpage 구현
  src/components/feature/CategoryList/CategoryList.style.ts
  src/components/feature/CatergoryForm/CategoryForm.style.ts
  src/components/feature/MainList/MainList.style.ts
  src/components/feature/MainList/MainList.tsx
  src/pages/categories/CategoriesPage.style.ts
  src/pages/main/MainPage.tsx
  src/utils/dummy.ts
  src/utils/sortedSchedule.ts
  src/utils/sortedTodo.ts
Labels: feature, design

#91 design: 그룹 생성 및 설정 페이지 퍼블리싱
  src/components/common/Circle/CircleInput.tsx
  src/components/feature/GroupNewPage/MemberList.style.ts
  src/components/feature/GroupNewPage/MemberList.tsx
  src/components/layout/NavBar/NavBar.tsx
  src/hooks/useGroupEditForm.ts
  src/hooks/useGroupNewForm.ts
  src/pages/group/edit/GroupEditPage.style.ts
  src/pages/group/edit/GroupEditPage.tsx
  src/pages/group/new/GroupNewPage.style.ts
  src/pages/group/new/GroupNewPage.tsx
Labels: design

#94 fix: 스토리북 오류 해결
  src/components/common/Button/Button.stories.tsx
  src/components/common/ScheduleList/ScheduleItem.stories.tsx
  src/components/common/SelectList/Category/Category.stories.tsx
  src/components/common/TimeInput/TimeInput.stories.tsx
  src/components/common/TodoList/TodoItem.stories.tsx
  src/components/common/Toggle/Toggle.stories.tsx
Labels: fix

#96 fix: routes파일 groupEdit 오류 수정
  src/pages/group/edit/GroupEditPage.tsx
Labels: bug

#97 refactor: layout 관련 컴포넌트 수정
  src/components/layout/Header/Header.style.ts
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/headerConfig.ts
  src/components/layout/NavBar/NavBar.style.ts
  src/components/layout/NavBar/NavBar.tsx
  src/components/layout/NavBar/navConfig.ts
  src/components/layout/RootLayout/RootLayout.style.tsx
  src/components/layout/RootLayout/RootLayout.tsx
  src/index.css
  src/mocks/PERSONAL_EVENT_DATA.ts
  src/mocks/PERSONAL_TODO_DATA.ts
  src/pages/main/MainPage.tsx
  src/routes.tsx
Labels: feature, fix, design, refactor

#99 feat: Calendar, Main page 개선
  src/components/common/Calendar/Calendar.style.ts
  src/components/common/Calendar/Calendar.tsx
  src/components/common/ScheduleItem/ScheduleItem.stories.tsx
  src/components/common/ScheduleItem/ScheduleItem.style.tsx
  src/components/common/ScheduleItem/ScheduleItem.tsx
  src/components/common/ScheduleList/ScheduleList.tsx
  src/components/common/TodoItem/TodoItem.stories.tsx
  src/components/common/TodoItem/TodoItem.style.tsx
  src/components/common/TodoItem/TodoItem.tsx
  src/components/common/TodoList/TodoList.tsx
  src/components/feature/MainCategoryButton/MainCategoryButton.tsx
  src/components/feature/MainList/MainList.tsx
  src/components/feature/main/CategoryButtons/CategoryButtons.style.ts
  src/components/feature/main/CategoryButtons/CategoryButtons.tsx
  src/hooks/queries/index.ts
  src/hooks/queries/useCategories.ts
  src/hooks/queries/useGroupSchedules.ts
  src/hooks/queries/useGroupTodos.ts
  src/hooks/queries/useGroups.ts
  src/hooks/queries/usePersonalGroupSchedules.ts
  src/hooks/queries/usePersonalGroupTodos.ts
  src/hooks/queries/usePersonalSchedules.ts
  src/hooks/queries/usePersonalTodos.ts
  src/hooks/useCalendar.ts
  src/mocks/CTEGORY_DATA.ts
  src/mocks/PERSONAL_EVENT_DATA.ts
  src/pages/main/MainPage.tsx
Labels: feature, design, refactor

#100 design: 마이페이지 및 내 정보 수정 페이지 퍼블리싱
  src/components/common/Button/Button.tsx
  src/hooks/useEditPage.ts
  src/pages/mypage/MyPage.style.ts
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/edit/MyEditPage.style.ts
  src/pages/mypage/edit/MyEditPage.tsx
Labels: feature, design

#102 feat: API 인스턴스 생성
  src/apis/apiService.ts
  src/apis/dummy.ts
  src/apis/todoAPI.ts
  src/hooks/queries/usePersonalTodos.ts
  src/types/todo.types.ts
Labels: feature

#106 hotfix: yarn build 오류 수정
  src/components/common/Calendar/Calendar.tsx
  src/hooks/useCalendar.ts
  src/pages/signup/SignupPage.tsx
Labels: bug, fix

#107 design: 그룹이 없을 경우 페이지 퍼블리싱
  src/pages/group/noData/GroupNoData.style.ts
  src/pages/group/noData/GroupNoData.tsx
  src/routes.tsx
Labels: design

#109 Feature/#103 common list
  src/components/common/Calendar/Calendar.tsx
  src/components/common/NewButton/NewButton.style.ts
  src/components/common/NewButton/NewButton.tsx
  src/components/common/ScheduleList/ScheduleList.tsx
  src/components/feature/MainList/MainList.tsx
  src/components/feature/dummy.ts
  src/components/feature/main/ScheduleList/ScheduleList.tsx
  src/components/feature/main/TodoList/TodoList.tsx
  src/hooks/queries/usePersonalTodos.ts
  src/hooks/useCalendar.ts
  src/hooks/useMainPage.ts
  src/mocks/CTEGORY_DATA.ts
  src/models/CalendarSchedule.ts
  src/models/CalendarTodo.ts
  src/pages/main/MainPage.style.ts
  src/pages/main/MainPage.tsx
  src/types/category.type.ts
  src/types/groupSchedule.type.ts
  src/types/groupTodo.type.ts
  src/types/index.ts
  src/types/personalGroupSchedule.type.ts
  src/types/personalGroupTodo.type.ts
  src/types/personalSchedule.type.ts
  src/types/personalTodo.type.ts
Labels: feature

#114 chore: 배포 관련 설정
  src/components/feature/main/ScheduleList/ScheduleList.tsx
  src/hooks/queries/usePersonalTodos.ts
  src/hooks/useMainPage.ts
  vercel.json
Labels: docs, setting

#117 feat: 메인 페이지 스타일 작업, 기능 추가
  src/components/common/Calendar/Calendar.tsx
  src/components/common/TextDate/TextDate.style.tsx
  src/components/feature/main/CategoryButtons/CategoryButtons.style.ts
  src/components/feature/main/CategoryButtons/CategoryButtons.tsx
  src/components/feature/main/ScheduleItem/ScheduleItem.style.ts
  src/components/feature/main/ScheduleItem/ScheduleItem.tsx
  src/components/feature/main/ScheduleList/ScheduleList.styled.ts
  src/components/feature/main/ScheduleList/ScheduleList.tsx
  src/components/feature/main/TodoItem/TodoItem.styled.ts
  src/components/feature/main/TodoItem/TodoItem.tsx
  src/components/feature/main/TodoList/TodoList.style.ts
  src/components/feature/main/TodoList/TodoList.tsx
  src/hooks/useCalendar.ts
  src/hooks/useMainPage.ts
  src/index.css
  src/mocks/PERSONAL_TODO_DATA.ts
  src/models/CalendarSchedule.ts
  src/models/MainSchedule.ts
  src/models/MainTodo.ts
  src/pages/main/MainPage.style.ts
  src/pages/main/MainPage.tsx
  src/types/personalGroupSchedule.type.ts
  src/types/personalGroupTodo.type.ts
  src/utils/mainPage/filterByDate.ts
  src/utils/mainPage/getCategoryColor.ts
  src/utils/mainPage/sortScheduleItems.ts
  src/utils/mainPage/sortTodoItems.ts
Labels: feature, design

#119 feat: 알림 페이지 퍼블리싱
  src/components/feature/notifications/GroupInviteForm/GroupInviteForm.style.ts
  src/components/feature/notifications/GroupInviteForm/GroupInviteForm.tsx
  src/components/feature/notifications/ScheduleForm/ScheduleForm.style.ts
  src/components/feature/notifications/ScheduleForm/ScheduleForm.tsx
  src/pages/notifications/Notifications.style.ts
  src/pages/notifications/NotificationsPage.tsx
  src/types/notification.ts
Labels: feature, design

#123 feat: 로그인, 회원가입 api 연동
  src/apis/apiService.ts
  src/apis/user/postLogin.ts
  src/apis/user/postSignup.ts
  src/hooks/useLoginForm.ts
  src/hooks/useSignupForm.ts
  src/pages/signup/SignupPage.tsx
  src/store/useAuthStore.ts
Labels: feature

#125 feat: API 파일 작업 및 API 연결
  src/App.tsx
  src/apis/apiService.ts
  src/apis/categories.ts
  src/apis/personalSchdule.ts
  src/apis/personalTodos.ts
  src/apis/todoAPI.ts
  src/components/common/SelectList/Category/CategorySelect.tsx
  src/components/form/TodoScheduleForm/TodoScheduleForm.tsx
  src/components/form/TodoScheduleForm/utils.ts
  src/hooks/queries/index.ts
  src/hooks/queries/useCategories.ts
  src/hooks/queries/usePersonalTodos.ts
  src/hooks/useMainPage.ts
  src/hooks/useTodoScheduleForm.ts
  src/pages/main/todo/edit/MainTodoEditPage.tsx
  src/pages/main/todo/new/MainTodoNewPage.tsx
  src/pages/notifications/NotificationsPage.tsx
  src/types/apiRequest.type.ts
  src/types/apiResponse.type.ts
  src/types/notification.types.ts
  src/types/select.types.ts
  src/types/todo.types.ts
  src/utils/date.ts
  vite.config.ts
Labels: feature, refactor, docs

#127 hotfix: 새로고침 해도 토큰 유지
  src/store/useAuthStore.ts
Labels: bug

#129 feat: 개인 일정 생성/수정 API 연결
  src/apis/personalSchdule.ts
  src/components/common/TextInput/TextInput.tsx
  src/hooks/queries/index.ts
  src/hooks/queries/usePersonalSchedules.ts
  src/hooks/queries/usePersonalTodos.ts
  src/hooks/useTodoScheduleForm.ts
  src/pages/main/schedule/edit/MainScheduleEditPage.tsx
  src/pages/main/schedule/new/MainScheduleNewPage.tsx
  src/pages/main/todo/edit/MainTodoEditPage.tsx
  src/pages/signup/SignupPage.tsx
  src/types/apiRequest.type.ts
  src/utils/date.ts
Labels: feature, fix

#132 feat: 그룹 투두 생성/수정 API 연결
  src/apis/groupTodos.ts
  src/apis/groups.ts
  src/components/common/SelectList/Group/GroupSelect.tsx
  src/components/form/TodoScheduleForm/TodoScheduleForm.tsx
  src/components/form/TodoScheduleForm/utils.ts
  src/hooks/queries/index.ts
  src/hooks/queries/useGroupTodos.ts
  src/hooks/queries/usePersonalSchedules.ts
  src/hooks/useTodoScheduleForm.ts
  src/pages/group/todo/edit/GroupTodoEditPage.tsx
  src/pages/group/todo/new/GroupTodoNewPage.tsx
  src/types/apiRequest.type.ts
  src/types/apiResponse.type.ts
  src/types/select.types.ts
Labels: feature

#134 feat: 그룹 일정 생성/수정 API 연결
  src/apis/groupSchdules.ts
  src/hooks/queries/index.ts
  src/hooks/queries/useGroupSchedules.ts
  src/hooks/useTodoScheduleForm.ts
  src/pages/group/schedule/edit/GroupScheduleEditPage.tsx
  src/pages/group/schedule/new/GroupScheduleNewPage.tsx
  src/pages/group/todo/edit/GroupTodoEditPage.tsx
  src/pages/group/todo/new/GroupTodoNewPage.tsx
  src/types/apiRequest.type.ts
Labels: feature, fix

#137 feat: 메인 페이지 API 작업 및 기능 추가
  dev-dist/registerSW.js
  dev-dist/sw.js
  dev-dist/workbox-54d0af47.js
  src/apis/personalSchdule.ts
  src/apis/personalTodos.ts
  src/components/common/Calendar/Calendar.tsx
  src/components/feature/main/CategoryButtons/CategoryButtons.tsx
  src/components/feature/main/CategoryFilter/CategoryFilter.style.ts
  src/components/feature/main/CategoryFilter/CategoryFilter.tsx
  src/components/feature/main/CategoryFilterList/CategoryFilterItem.style.ts
  src/components/feature/main/CategoryFilterList/CategoryFilterItem.tsx
  src/components/feature/main/ScheduleItem/ScheduleItem.tsx
  src/components/feature/main/TodoItem/TodoItem.tsx
  src/components/layout/Header/Header.style.ts
  src/hooks/queries/index.ts
  src/hooks/queries/useCategories.ts
  src/hooks/queries/usePersonalGroupSchedules.ts
  src/hooks/queries/usePersonalGroupTodos.ts
  src/hooks/queries/usePersonalSchedules.ts
  src/hooks/queries/usePersonalTodos.ts
  src/hooks/useMainPage.ts
  src/mocks/CTEGORY_DATA.ts
  src/mocks/PERSONAL_EVENT_DATA.ts
  src/mocks/PERSONAL_TODO_DATA.ts
  src/models/MainSchedule.ts
  src/models/MainTodo.ts
  src/pages/main/MainPage.tsx
  src/store/categoryStore.ts
  src/store/dummy.ts
  src/types/apiRequest.type.ts
  src/utils/mainPage/filterByCategory.ts
  src/utils/mainPage/sortScheduleItems.ts
  src/utils/mainPage/sortTodoItems.ts
Labels: feature, refactor

#138 feat: 그룹 페이지 api 연동
  src/apis/apiService.ts
  src/apis/group/deleteMember.ts
  src/apis/group/getGroup.ts
  src/apis/group/getMember.ts
  src/apis/group/postGroup.ts
  src/apis/group/postInvitation.ts
  src/apis/group/putGroup.ts
  src/components/feature/GroupNewPage/MemberList.tsx
  src/hooks/useGroupEditForm.ts
  src/hooks/useGroupNewForm.ts
  src/hooks/useInviteMember.ts
  src/hooks/useMemberList.ts
  src/pages/group/edit/GroupEditPage.tsx
  src/pages/group/new/GroupNewPage.tsx
  src/pages/group/noData/GroupNoData.tsx
  src/store/useAuthStore.ts
Labels: feature

#141 design: 온보딩페이지 퍼블리싱
  src/assets/icons/bulb.svg
  src/assets/onboard/logo.png
  src/components/layout/RootLayout/RootLayout.tsx
  src/pages/home/HomePage.style.ts
  src/pages/home/HomePage.tsx
Labels: design

#142 feat: 마이페이지 정보 조회 및 수정
  src/apis/apiService.ts
  src/apis/mypage/getUser.ts
  src/apis/mypage/postLogout.ts
  src/apis/mypage/putUser.ts
  src/assets/icons/pencil.svg
  src/hooks/useEditPage.ts
  src/pages/mypage/MyPage.style.ts
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/edit/MyEditPage.tsx
Labels: feature

#144 feat: 개인 투두&일정의 생성&수정 페이지 다른 페이지와 연결
  src/components/feature/main/TodoItem/TodoItem.tsx
  src/components/form/TodoScheduleForm/utils.ts
  src/hooks/useTodoScheduleForm.ts
  src/pages/main/schedule/edit/MainScheduleEditPage.tsx
  src/pages/main/schedule/new/MainScheduleNewPage.tsx
  src/pages/main/todo/edit/MainTodoEditPage.tsx
  src/pages/main/todo/new/MainTodoNewPage.tsx
Labels: feature

#146 feat: 그룹 페이지 구현
  package.json
  src/apis/groups.ts
  src/components/feature/group/GroupPick/GroupPick.style.ts
  src/components/feature/group/GroupPick/GroupPick.tsx
  src/components/feature/group/MainList/GroupList.style.ts
  src/components/feature/group/MainList/GroupList.tsx
  src/components/feature/group/ProfileSlider/ProfileSlider.style.ts
  src/components/feature/group/ProfileSlider/ProfileSlider.tsx
  src/components/feature/group/ScheduleItem/GroupScheduleItem.style.ts
  src/components/feature/group/ScheduleItem/GroupScheduleItem.tsx
  src/components/feature/group/TodoItem/GroupTodoItem.style.ts
  src/components/feature/group/TodoItem/GroupTodoItem.tsx
  src/hooks/queries/useGroupData.ts
  src/hooks/queries/useGroups.ts
  src/pages/group/GroupPage.tsx
  src/types/category.type.ts
  src/types/groupSchedule.type.ts
  src/types/groupTodo.type.ts
  src/types/select.types.ts
  src/utils/sortedGroup.ts
  src/utils/sortedGroupSchedule.ts
Labels: feature, design, refactor

#150 feat: 그룹 투두/일정 생성/수정 페이지 다른 페이지와 연결
  src/components/feature/group/MainList/GroupList.tsx
  src/pages/group/schedule/edit/GroupScheduleEditPage.tsx
  src/pages/group/schedule/new/GroupScheduleNewPage.tsx
  src/pages/group/todo/edit/GroupTodoEditPage.tsx
  src/pages/group/todo/new/GroupTodoNewPage.tsx
Labels: feature

#152 feat: 그룹 투두 개발 및 코드 수정
  src/apis/groups.ts
  src/components/feature/group/GroupPick/GroupPick.style.ts
  src/components/feature/group/GroupPick/GroupPick.tsx
  src/components/feature/group/MainList/GroupList.tsx
  src/components/feature/group/ScheduleItem/GroupScheduleItem.tsx
  src/components/feature/group/TodoItem/GroupTodoItem.style.ts
  src/components/feature/group/TodoItem/GroupTodoItem.tsx
  src/hooks/queries/useGroupSchedules.ts
  src/hooks/queries/useGroupTodos.ts
  src/hooks/queries/useGroups.ts
  src/hooks/useUserNames.ts
  src/pages/group/GroupPage.tsx
Labels: feature, fix, refactor

#154 feat: 그룹 데이터 없을 경우 및 수정 페이지 로직 수정
  src/components/feature/GroupNewPage/MemberList.tsx
  src/hooks/useGroupEditForm.ts
  src/pages/group/edit/GroupEditPage.tsx
  src/pages/group/noData/GroupNoData.tsx
Labels: feature, fix

#155 feat: 실시간 알림 기능 구현
  dev-dist/registerSW.js
  dev-dist/sw.js
  dev-dist/workbox-54d0af47.js
  package.json
  src/apis/alarm.ts
  src/apis/apiService.ts
  src/components/feature/header/AlarmIcon.style.ts
  src/components/feature/header/AlarmIcon.tsx
  src/components/feature/notifications/GroupInviteForm/GroupInviteForm.tsx
  src/components/feature/notifications/ScheduleForm/ScheduleForm.tsx
  src/components/layout/Header/Header.tsx
  src/pages/notifications/Notifications.style.ts
  src/pages/notifications/NotificationsPage.tsx
  src/store/useNotification.store.ts
  src/types/notification.types.ts
  src/utils/alarm.ts
Labels: feature, fix

#156 feat: 그룹 페이지 추가 수정
  src/assets/icons/logo.svg
  src/components/common/DeleteConfirm/DeleteConfirm.style.ts
  src/components/common/DeleteConfirm/DeleteConfirm.tsx
  src/components/common/SelectList/Category/CategorySelect.tsx
  src/components/feature/group/GroupPick/GroupPick.style.ts
  src/components/feature/group/GroupPick/GroupPick.tsx
  src/components/feature/group/MainList/GroupList.style.ts
  src/components/feature/group/MainList/GroupList.tsx
  src/components/feature/group/ProfileSlider/ProfileSlider.style.ts
  src/components/feature/group/ProfileSlider/ProfileSlider.tsx
  src/components/feature/group/ScheduleItem/GroupScheduleItem.tsx
  src/components/feature/group/TodoItem/GroupTodoItem.style.ts
  src/components/feature/group/TodoItem/GroupTodoItem.tsx
  src/components/layout/Header/Header.tsx
  src/hooks/queries/useUser.ts
  src/pages/group/GroupPage.tsx
Labels: feature, design, refactor

#159 fix: 헤더 에러 해결
  src/components/layout/Header/Header.tsx
Labels: fix

#162 fix:그룹멤버 선택 에러 수정 및 코드 수정
  src/components/common/SelectList/Group/GroupSelect.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/headerConfig.ts
  src/pages/categories/CategoriesPage.tsx
  src/pages/categories/edit/CategoriesEditPage.tsx
  src/pages/group/schedule/edit/GroupScheduleEditPage.tsx
  src/pages/group/todo/edit/GroupTodoEditPage.tsx
Labels: fix

#163 feat: 메인 페이지 관련 오류 수정
  src/apis/personalTodos.ts
  src/components/common/Calendar/Calendar.tsx
  src/components/common/Circle/CircleInput.tsx
  src/components/feature/main/ScheduleList/ScheduleList.styled.ts
  src/components/feature/main/ScheduleList/ScheduleList.tsx
  src/components/feature/main/TodoItem/TodoItem.tsx
  src/components/feature/main/TodoList/TodoList.style.ts
  src/components/feature/main/TodoList/TodoList.tsx
  src/components/form/TodoScheduleForm/TodoScheduleForm.style.ts
  src/hooks/queries/useCategories.ts
  src/hooks/queries/usePersonalGroupTodos.ts
  src/hooks/useMainPage.ts
  src/models/MainSchedule.ts
  src/models/MainTodo.ts
  src/pages/group/GroupPage.tsx
  src/pages/main/MainPage.tsx
  src/utils/mainPage/filterByCategory.ts
Labels: feature, fix, refactor

#166 fix: 버그 수정
  src/components/common/Calendar/Calendar.style.ts
  src/components/common/Calendar/Calendar.tsx
  src/components/feature/GroupNewPage/MemberList.style.ts
  src/components/feature/GroupNewPage/MemberList.tsx
  src/components/layout/Header/Header.style.ts
  src/hooks/useChat.ts
  src/hooks/useCircleInput.ts
  src/hooks/useGroupEditForm.ts
  src/hooks/useGroupNewForm.ts
  src/hooks/useMainPage.ts
  src/pages/group/GroupPage.tsx
  src/pages/group/edit/GroupEditPage.tsx
  src/pages/group/noData/GroupNoData.tsx
  src/pages/group/schedule/edit/GroupScheduleEditPage.tsx
  src/pages/group/schedule/new/GroupScheduleNewPage.tsx
  src/pages/main/MainPage.tsx
  src/pages/mypage/MyPage.style.ts
  src/pages/mypage/MyPage.tsx
Labels: feature, fix, design, refactor

#164 fix: 배포 관련 오류 해결
  index.html
  src/apis/apiService.ts
  src/components/common/SelectList/Category/Category.stories.tsx
  src/components/common/SelectList/Group/GroupSelect.stories.tsx
  src/components/feature/header/AlarmIcon.tsx
  src/hooks/queries/usePersonalGroupSchedules.ts
  src/hooks/queries/usePersonalSchedules.ts
  src/hooks/queries/usePersonalTodos.ts
  vercel.json
Labels: fix

#168 refactor: 로고 수정 및 버그 해결
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/assets/PlanWith_Logo.svg
  src/assets/icons/logo.svg
  src/components/common/Calendar/Calendar.style.ts
  src/components/layout/Header/Header.style.ts
  src/components/layout/Header/Header.tsx
  src/hooks/queries/useCategories.ts
  src/hooks/queries/useGroupSchedules.ts
  src/hooks/queries/useGroupTodos.ts
  src/hooks/queries/usePersonalSchedules.ts
  src/hooks/queries/usePersonalTodos.ts
  src/hooks/useLoginForm.ts
  src/index.css
  src/pages/categories/edit/CategoriesEditPage.tsx
  src/pages/group/schedule/edit/GroupScheduleEditPage.tsx
  src/pages/group/schedule/new/GroupScheduleNewPage.tsx
  src/pages/group/todo/edit/GroupTodoEditPage.tsx
  src/pages/group/todo/new/GroupTodoNewPage.tsx
  src/pages/home/HomePage.style.ts
  src/pages/home/HomePage.tsx
  src/pages/login/LoginPage.style.ts
  src/pages/login/LoginPage.tsx
  src/pages/main/schedule/edit/MainScheduleEditPage.tsx
  src/pages/main/schedule/new/MainScheduleNewPage.tsx
  src/pages/main/todo/edit/MainTodoEditPage.tsx
  src/pages/main/todo/new/MainTodoNewPage.tsx
Labels: bug, feature, fix, design, refactor

#169 fix: 실시간 알림 에러 해결
  src/apis/alarm.ts
  src/components/feature/header/AlarmIcon.tsx
  src/components/feature/notifications/GroupInviteForm/GroupInviteForm.tsx
  src/pages/notifications/NotificationsPage.tsx
  src/types/notification.types.ts
  src/utils/alarm.ts
Labels: fix

#171 docs: README.md 초안 작성
  README.md
  public/README/PlanWith_Logo.png
Labels: docs
